# f1=open("file_1.txt","w+")
# print(f1.tell())
# f1.write("hello india i am varad")
# print(f1.tell())
# data=f1.read()
# print(data)
# print(f1.tell())
# f1.close()
f1=open("","a+")
print(f1.tell())
f1.write("hello")
print(f1.read())
f1.write("varad op")